[application]
name = "dioxus-editor"
default_platform = "web"
out_dir = "dist"
asset_dir = "public"

[web.app]
title = "dioxus-editor"

[web.resource]
style = []
script = []

[web.resource.dev]
# Javascript code file
# serve: [dev-server] only
script = []
